### ISSUE TITLE
File with semicolon in filename fails with confusing notice

### ISSUE THREAD

**Issue by visualwritings** [humhub/cfiles#91] opened 2020-09-21 10:22 UTC
Hi,
A client for which I've setup humhub was complaining one of the members couldn't upload files, because he got the notice 'You are not allowed to run this action'. After fiddling around with permissions, testing with various browser and impersonating that specific account I couldn't find why he would lack permission to upload a file, which was what the notice for me implied (I realise I made an assumption here though). It turned out to only to concern a specific file (he didn't test any other files) with a semicolon in the filename.
I would expect humhub to either sanitize the filename, or to give a more descriptive notice regarding the issue. The upload does produce a notice in the log, mentioning a partially uploaded file.
~Martijn

**Comment by fae7em** [comment] 2020-09-21 19:06
Hi @visualwritings,
Could you please give the name of file and version of cfile module which used in your project?
Because I tried to upload some files with semicolon in their names and there was no problem in uploading them : 

<img width="988" alt="Screenshot 2020-09-21 at 21 00 43" src="https://user-images.githubusercontent.com/66942918/93809500-a2aab800-fc4d-11ea-90bd-8c490dd86a6c.png">

and also I tried a file with a colon in its name and I get this message : 
<img width="975" alt="Screenshot 2020-09-21 at 21 04 28" src="https://user-images.githubusercontent.com/66942918/93809922-2ebcdf80-fc4e-11ea-903e-6ba0a35449bd.png">

Maybe the reason of the issue is something else, or maybe it occurs in some previous versions.

**Comment by visualwritings** [comment] 2020-09-22 07:29
hi @fae7em ,

I've just tested the same scenario on a different humhub install, which indeed works fine. For sake of completeness I'll put some additional information below, but for now my assumption would be to look at the webserver rather than cfiles or humhub. I can update this ticket for future reference when I find the issue.

Thanks.

-----

I'm running the latest version 0.11.19. Humhub wasn't the latest version though, so I've updated to the latest but it doesn't make a difference.
We're running PHP 7.3.22 on Litespeed. 
When I open up the notice it shows a 403 response from the webserver:
![screengrab-notice-fileupload-semicolon](https://user-images.githubusercontent.com/7559521/93853756-bf2e0b00-fcb4-11ea-8412-da4641746635.png)
The filename I'm trying to upload is **NEN-EN-ISO 9001 2015 en;nl.pdf**

**Comment by yurabakhtin** [comment] 2021-08-02 08:28
@visualwritings Hello, I tested an uploading the file with name `NEN-EN-ISO 9001 2015 en;nl.pdf`:

<img width="964" alt="test_file_name" src="https://user-images.githubusercontent.com/6995524/127829092-208be4c2-03b2-4c83-87f5-02083f94deb1.png">

CFiles: 0.11.20
HumHub: 1.9.1 (Unreleased), branch `master`
PHP: 7.3.9

**Comment by luke-** [comment] 2021-08-02 08:42
@yurabakhtin Thanks, then let's close this for now.

@visualwritings Please reopen when problem still is open.

**Closed by luke-** 2021-08-02 08:42 UTC
Labels: bug
