### ISSUE TITLE
Cannot delete files or folders

### ISSUE THREAD

**Issue by thezonemedia** [humhub/cfiles#160] opened 2022-11-03 03:27 UTC
get a nasty error.. and even uninstalling the module doesnt work... gives: 
Unknown Property – [yii\base\UnknownPropertyException](http://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html)
Getting unknown property: humhub\modules\file\models\File::content

this basically crashes my site.. i cannot delete content anyhwere after this error.
here is the trace from the original attempt to delete a file:

ive rebuilt integrity etc no help

 "url": "/s/test/cfiles/delete?fid=17",
    "status": 500,
    "response": "<pre>Exception (Unknown Property) 'yii\\base\\UnknownPropertyException' with message 'Getting unknown property: humhub\\modules\\file\\models\\File::content' \n\nin /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\\base\\Component-&gt;__get('content')\n#1 /home/holosailhaven/public_html/protected/modules/mentionedUsers/Events.php(20): yii\\db\\BaseActiveRecord-&...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception (Unknown Property) 'yii\\base\\UnknownPropertyException' with message 'Getting unknown property: humhub\\modules\\file\\models\\File::content' \n\nin /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\\base\\Component-&gt;__get('content')\n#1 /home/holosailhaven/public_html/protected/modules/mentionedUsers/Events.php(20): yii\\db\\BaseActiveRecord-&gt;__get('content')\n#2 [internal function]: humhub\\modules\\mentionedUsers\\Events::onContentDelete(Object(yii\\base\\ModelEvent))\n#3 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\\base\\ModelEvent))\n#4 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\\base\\Event::trigger('humhub\\\\componen...', 'beforeDelete', Object(yii\\base\\ModelEvent))\n#5 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1025): yii\\base\\Component-&gt;trigger('beforeDelete', Object(yii\\base\\ModelEvent))\n#6 /home/holosailhaven/public_html/protected/humhub/modules/file/models/File.php(143): yii\\db\\BaseActiveRecord-&gt;beforeDelete()\n#7 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754): humhub\\modules\\file\\models\\File-&gt;beforeDelete()\n#8 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\\db\\ActiveRecord-&gt;deleteInternal()\n#9 /home/holosailhaven/public_html/protected/humhub/modules/file/Events.php(90): yii\\db\\ActiveRecord-&gt;delete()\n#10 [internal function]: humhub\\modules\\file\\Events::onBeforeActiveRecordDelete(Object(yii\\base\\ModelEvent))\n#11 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\\base\\ModelEvent))\n#12 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\\base\\Event::trigger('humhub\\\\componen...', 'beforeDelete', Object(yii\\base\\ModelEvent))\n#13 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1025): yii\\base\\Component-&gt;trigger('beforeDelete', Object(yii\\base\\ModelEvent))\n#14 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754): yii\\db\\BaseActiveRecord-&gt;beforeDelete()\n#15 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\\db\\ActiveRecord-&gt;deleteInternal()\n#16 /home/holosailhaven/public_html/protected/modules/cfiles/controllers/DeleteController.php(40): yii\\db\\ActiveRecord-&gt;delete()\n#17 [internal function]: humhub\\modules\\cfiles\\controllers\\DeleteController-&gt;actionIndex()\n#18 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#19 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#20 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller-&gt;runAction('', Array)\n#21 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction('cfiles/delete', Array)\n#22 /home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#23 /home/holosailhaven/public_html/index.php(25): yii\\base\\Application-&gt;run()\n#24 {main}</pre>",
        "status": 500,
        "statusText": "error"

**Comment by luke-** [comment] 2022-11-03 17:10
Can you reproduce this on a fresh installation?

**Comment by thezonemedia** [comment] 2022-11-03 17:14
no.. i recreated my instance and its ok now... just wondering what could have happened!

**Comment by luke-** [comment] 2022-11-03 18:05
Hmm, did you ran an integry check?

**Comment by thezonemedia** [comment] 2022-11-03 19:12
yea i did... i reconciled a bunch of things and it came back, but i could not delete files or delete posts anymore... started over... so far so good.. hoping it doesnt happen again!

that being said... do you know of a freichat clone that is more maintained... really could use real time chat for humhub

**Comment by yurabakhtin** [comment] 2022-11-08 15:21
@thezonemedia @luke- I could not reproduce this on module `cfiles`, but I have investigated the log by adding new lines, so we have this:

```

Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Getting unknown property: humhub\modules\file\models\File::content' \n\nin
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get('content')\n#1
/home/holosailhaven/public_html/protected/modules/mentionedUsers/Events.php(20): yii\db\BaseActiveRecord->__get('content')\n#2
[internal function]: humhub\modules\mentionedUsers\Events::onContentDelete(Object(yii\base\ModelEvent))\n#3
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\ModelEvent))\n#4
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('humhub\\componen...', 'beforeDelete', Object(yii\base\ModelEvent))\n#5
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1025): yii\base\Component->trigger('beforeDelete', Object(yii\base\ModelEvent))\n#6
/home/holosailhaven/public_html/protected/humhub/modules/file/models/File.php(143): yii\db\BaseActiveRecord->beforeDelete()\n#7
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754): humhub\modules\file\models\File->beforeDelete()\n#8
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\db\ActiveRecord->deleteInternal()\n#9
/home/holosailhaven/public_html/protected/humhub/modules/file/Events.php(90): yii\db\ActiveRecord->delete()\n#10
[internal function]: humhub\modules\file\Events::onBeforeActiveRecordDelete(Object(yii\base\ModelEvent))\n#11
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\ModelEvent))\n#12
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('humhub\\componen...', 'beforeDelete', Object(yii\base\ModelEvent))\n#13
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1025): yii\base\Component->trigger('beforeDelete', Object(yii\base\ModelEvent))\n#14
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754): yii\db\BaseActiveRecord->beforeDelete()\n#15
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\db\ActiveRecord->deleteInternal()\n#16
/home/holosailhaven/public_html/protected/modules/cfiles/controllers/DeleteController.php(40): yii\db\ActiveRecord->delete()\n#17
[internal function]: humhub\modules\cfiles\controllers\DeleteController->actionIndex()\n#18
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#19
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)\n#20
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)\n#21
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('cfiles/delete', Array)\n#22
/home/holosailhaven/public_html/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))\n#23
/home/holosailhaven/public_html/index.php(25): yii\base\Application->run()\n#24 {main}
```

as we can see on 4th line from top - `/protected/modules/mentionedUsers/Events.php(20):`,
we don't have the module `mentionedUsers` on humhub github but I found it by google here https://github.com/maxal-studio/humhub-mentionedUsers,
if it is the same module what we need then next we can see on the 20th line here https://github.com/maxal-studio/humhub-mentionedUsers/blob/master/Events.php#L20 - `$shares = models\Share::findAll(['content_id' => $event->sender->content->id]);`,
here the `$event->sender` may has no the property `content`, it is why the error occurred,
if we will look at the config https://github.com/maxal-studio/humhub-mentionedUsers/blob/master/config.php we see the event is called for the class `humhub\components\ActiveRecord` and not for `humhub\modules\content\components\ContentActiveRecord` as should be.

I can suggest one of the 2 solutions:

1. Modify the config to:

```
            'class' => ContentActiveRecord::className(),
            'event' => ContentActiveRecord::EVENT_BEFORE_DELETE,
```

2. Modify the code of the `public static function onContentDelete($event)` to call it only by condition like:

```php
if ($event->sender instanceof humhub\modules\content\components\ContentActiveRecord) {
```

I prefer the 1st solution because it seems it was planned to be developed only for Content Active Records, even if we look at the method is named as `onContentDelete` and not like `onActiveRecordDelete`.

**Comment by thezonemedia** [comment] 2022-11-08 15:35
wow thanks for this response! that for sure is the issue!  ty!

**Comment by luke-** [comment] 2022-11-08 15:54
@yurabakhtin Thanks for the investigation & solution. Let's close this issue here.

**Closed by luke-** 2022-11-08 15:54 UTC
Labels: need investigation
